name: Release
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: docker.cloudsmith.io
          username: ${{ secrets.CLOUDSMITH_API_KEY_USERNAME }}
          password: ${{ secrets.CLOUDSMITH_API_KEY }}

      - run: |
          name=docker.cloudsmith.io/automodality/public/plotjuggler:latest
          docker build . -t "$name"
          docker push "$name"